server:
  port: 8003

spring:
  application:
    # service name
    name: provider-payment-service-zookeeper
  cloud:
    zookeeper: # zookeeper
      connect-string: localhost:2181
      discovery:
        instance-id: provider-payment-8003
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    # MySQL credentials
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.redlogo.cloud.entities
