server:
  port: 8004

spring:
  application:
    # service name
    name: provider-payment-service-consul
  cloud:
    consul: # consul
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        instance-id: provider-payment-8004
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    # MySQL credentials
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.redlogo.cloud.entities
