server:
  port: 94

spring:
  application:
    name: consumer-order-sleuth-service
  # zipkin
  zipkin:
    base-url: http://localhost:9411
  # sleuth
  sleuth:
    sampler:
      # sample rate
      probability: 1

eureka:
  client:
    # register to eureka
    register-with-eureka: true
    # if multiple nodes, must be true for load balancing with ribbon
    fetch-registry: true
    service-url:
      # single node
      # defaultZone: http://localhost:7001/eureka
      # multiple nodes
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    # name on eureka
    instance-id: consumer-order-sleuth-94
    # display IP on path of eureka
    prefer-ip-address: true