server:
  port: 81

spring:
  application:
    name: consumer-order-service

eureka:
  client:
    # register to eureka
    register-with-eureka: true
    # if multiple nodes, must be true for load balancing with ribbon
    fetch-registry: true
    service-url:
      # single node
      # defaultZone: http://localhost:7001/eureka
      # multiple nodes
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    # name on eureka
    instance-id: consumer-order-81
    # display IP on path of eureka
    prefer-ip-address: true